export const ROUTER_PATH = {
  ROOT: '/',
  HOME: '/home'
}

export const ROUTER_NAME = {
  ROOT: 'root',
  HOME: 'home'
}

export const API_PATH = {
  CUSTOMER: '/customers'
}

export const LOCALE_KEY = {
  MESSAGE_ERROR: 'MESSAGE_ERROR',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  CANCEL_BTN: 'CANCEL_BTN',
  OK_BTN: 'OK_BTN',
  APP_NAME: 'APP_NAME',
  PAGE_TEXT: 'PAGE_TEXT',
  FIND_USER_LABEL: 'FIND_USER_LABEL',
  ADD_BTN: 'ADD_BTN',
  REMOVE_BTN: 'REMOVE_BTN',
  REMOVE_MULTIPLE_ITEMS_CONFIRM_MSG: 'REMOVE_MULTIPLE_ITEMS_CONFIRM_MSG',
  REMOVE_ITEM_CONFIRM_MSG: 'REMOVE_ITEM_CONFIRM_MSG',
  UPDATE_DATA_CONFIRM_MSG: 'UPDATE_DATA_CONFIRM_MSG',
  TITLE_DIALOG_CONFIRM: 'TITLE_DIALOG_CONFIRM',
  USER_NAME_LABEL: 'USER_NAME_LABEL',
  TAGS: 'TAGS',
  SAVE_BTN: 'SAVE_BTN',
  USER_NAME_TOO_LONG_ERROR_MSG: 'USER_NAME_TOO_LONG_ERROR_MSG',
  MESSAGE_UPDATE_SUCCESS: 'MESSAGE_UPDATE_SUCCESS',
  TITLE_EDIT_CUSTOMER_MODAL: 'TITLE_EDIT_CUSTOMER_MODAL',
  TITLE_ADD_CUSTOMER_MODAL: 'TITLE_ADD_CUSTOMER_MODAL',
  NOTICE_TAGS: 'NOTICE_TAGS',
  NO_DATA_TEXT: 'NO_DATA_TEXT',
  TOTAL_ITEM_PER_PAGE: 'TOTAL_ITEM_PER_PAGE',
  LOADING_DATA: 'LOADING_DATA',
  CREATED_DATE_LABEL: 'CREATED_DATE_LABEL',
  UPDATED_DATE_LABEL: 'UPDATED_DATE_LABEL',
  EDIT_LABEL: 'EDIT_LABEL',
  DELETE_LABEL: 'DELETE_LABEL',
  REMOVE_ITEM_SUCCESS_MSG: 'REMOVE_ITEM_SUCCESS_MSG'
}

export const CONSTANT = {
  STORE_ID_GET_LIST_USERS: 'get-list-user',
  STATUS_CODE_SUCCESS: 200,
  ITEM_PER_PAGE_OPTION: [
    { value: 15, title: '15' },
    { value: 30, title: '30' },
    { value: 50, title: '50' }
  ],
  CUSTOMER_ID_KEY: 'customer_id',
  ORDER: 'asc',
  CUSTOMER_NAME_LENGTH: 20,
  CHIP_LENGTH: 10,
  NUMBER_CHIP: 3,
  APPLICATION_JSON: 'application/json',
  CONTENT_TYPE: 'Content-Type',
  DATE_FORMAT: 'YYYY/MM/DD hh:mm A',
  TABLE_SELECTOR: 'table',
  SYSTEM_ERROR_MSG: 'System Error'
}
